camera:
  source: 0  # Default camera source (0 for default webcam)

llm:
  api_key: "your_openai_api_key"  # Replace with your OpenAI API key
  model: "gpt-4"  # LLM model to use

tts:
  voice: "en-US-Wavenet-D"  # Google TTS voice model
  speed: 1.0  # Speech speed

output:
  audio_device: "default"  # Default audio output device
  json_output_path: "output/detection_results.json"  # Path to save JSON output